### ISSUE TITLE
Crash on recursive definitions

### ISSUE THREAD

**Issue by hilkeheremans** [kogosoftwarellc/express-openapi-validation#1]
Contrary to what I said earlier, it seems ```express-openapi-validation``` does not support recursive object validations.

Attempting to start ```express-openapi``` with the following definition overloads my call stack:
````
{
  "swagger": "2.0",
  "info": {
    "description": "Recursive API",
    "version": "1.0.0",
    "title": "Recursive API",
    "contact": {},
    "license": {
      "name": "UNLICENSED"
    }
  },
  "host": "api.test.eu:443",
  "basePath": "/v1",
  "tags": [
    {
      "name": "Default",
      "description": "Default section"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {

  },
  "definitions": {
    "RecursiveDefinition": {
      "type": "object",
      "properties": {
        "recursives": {
          "type": "array",
          "description": "List of recursive definitions",
          "items": {
            "$ref": "#/definitions/RecursiveDefinition"
          }
        },
        "otherProp": {
          "description": "Some other property",
          "type": "string"
        }
      },
      "description": "A JSON object describing a Recursive object"
    }
 }
}
```

Would it be possible to investigate this? Unfortunately, this is blocking for me. Until resolution, I'll have to move back to an alternative.

**Comment by jsdevel** [comment]
@hilkeheremans this could be a limitation of jsonschema.  Checking...

**Comment by jsdevel** [comment]
Actually, I'm using a recursive definition in one of my other projects that's using `express-openapi`.  Can you output the error you get?

**Comment by jsdevel** [comment]
@hilkeheremans see https://github.com/kogosoftwarellc/express-openapi/commit/5f5c48f759ade41d83741767ea6077c696d25a90.  It works in the `basic-usage` project.  Let me know when you can paste the output of what you're seeing.

**Comment by jsdevel** [comment]
@hilkeheremans see https://github.com/kogosoftwarellc/express-openapi-validation/commit/e3a6d5f1181fc991e059199a420db1afcba0df55

Added tests here as well to verify that recursive definitions are supported.

**Comment by hilkeheremans** [comment]
@jsdevel Odd; it seems the issue doesn't occur on my other box, although the code isn't fully synced. I'll check it out more thoroughly as time permits (over the weekend). Will keep you updated & sorry to have you go through this trouble.

Thanks for adding an additional test though, always a good thing.

**Comment by jsdevel** [comment]
> sorry to have you go through this trouble.

Don't be!  My goal is to work through these types of things and you're helping out with that.  I look forward to any more feedback or questions you may have.
